apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: rabbitmq
  labels:
    app: rabbitmq-app
spec:
  ports:
  - port: 5672
    name: rabbitmq
  - port: 4369
    name: epmd
  clusterIP: None
  selector:
    app: rabbitmq-app
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: rabbitmq-management
  labels:
    app: rabbitmq-app
spec:
  type: LoadBalancer
  ports:
  - port: 15672
    name: rabbitmq-management
  selector:
    app: rabbitmq-app
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq-app
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: rabbit
        image: your_registry.your_domain:5000/rabbitmq
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
          name: external-port
        - containerPort: 4369
          name: empd
        - containerPort: 15672
          name: management
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        command:
        - /sbin/startup.py
        readinessProbe:
          exec:
            command:
            - test
            - -f
            - "/tmp/rabbit_ready"
          initialDelaySeconds: 1
          timeoutSeconds: 5
